name: 🗑️ Auto Camo Purge
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'URL to parse and purge'
        required: false
        default: ''
  schedule:
    - cron: '*/10 * * * *' # 10分おき

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      # 1. 引数（target_url）がある場合は、そのリポジトリのCamoをパージ
      - name: Purge Target Repository
        if: ${{ github.event.inputs.target != '' }}
        uses: koki-develop/hub-purge-action@c608e39abca23026c802f44643cffccc123a826f # v1.0.3
        with:
          repository: ${{ github.event.inputs.target }}

      # 2. 定期実行（または連動時）に自分のプロフィールページも常にパージ
      - name: Purge Profile Page
        uses: koki-develop/hub-purge-action@c608e39abca23026c802f44643cffccc123a826f # v1.0.3
        with:
          repository: neon-aiart/neon-aiart
